version: 2

jobs:
  main:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Check that the build runs
          command: npm run build

workflows:
  version: 2

  on-commit:
    jobs:
      - main
